// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesTime.DataAccess.Database;

#nullable disable

namespace MoviesTime.Contract.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230211121535_PluralizeTheaterTableName")]
    partial class PluralizeTheaterTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesTime.Contract.Models.Genres", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.Languages", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.MovieGenreMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MovieID1")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GenreID");

                    b.HasIndex("MovieID1");

                    b.ToTable("MovieGenreMapping");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.MovieLanguageMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageID1")
                        .HasColumnType("int");

                    b.Property<int>("MovieID1")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LanguageID1");

                    b.HasIndex("MovieID1");

                    b.ToTable("MovieLanguageMapping");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.MovieReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int?>("EditedFromReviewID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte>("MovieRating")
                        .HasColumnType("tinyint");

                    b.Property<int>("MoviesMovieID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsersUserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("MoviesMovieID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("MovieReview");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.Movies", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("MovieLength")
                        .HasColumnType("time");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheaterID1")
                        .HasColumnType("int");

                    b.HasKey("MovieID");

                    b.HasIndex("TheaterID1");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.TestModel", b =>
                {
                    b.Property<int>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestID");

                    b.ToTable("TestTable");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.Theaters", b =>
                {
                    b.Property<int>("TheaterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheaterID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerIDUserID")
                        .HasColumnType("int");

                    b.Property<string>("TheaterContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TheaterName")
                        .HasColumnType("int");

                    b.HasKey("TheaterID");

                    b.HasIndex("ManagerIDUserID");

                    b.ToTable("Theaters");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.MovieGenreMapping", b =>
                {
                    b.HasOne("MoviesTime.Contract.Models.Genres", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesTime.Contract.Models.Movies", "MovieID")
                        .WithMany()
                        .HasForeignKey("MovieID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MovieID");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.MovieLanguageMapping", b =>
                {
                    b.HasOne("MoviesTime.Contract.Models.Languages", "LanguageID")
                        .WithMany()
                        .HasForeignKey("LanguageID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesTime.Contract.Models.Movies", "MovieID")
                        .WithMany()
                        .HasForeignKey("MovieID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageID");

                    b.Navigation("MovieID");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.MovieReview", b =>
                {
                    b.HasOne("MoviesTime.Contract.Models.Movies", "Movies")
                        .WithMany()
                        .HasForeignKey("MoviesMovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesTime.Contract.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movies");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.Movies", b =>
                {
                    b.HasOne("MoviesTime.Contract.Models.Theaters", "TheaterID")
                        .WithMany()
                        .HasForeignKey("TheaterID1");

                    b.Navigation("TheaterID");
                });

            modelBuilder.Entity("MoviesTime.Contract.Models.Theaters", b =>
                {
                    b.HasOne("MoviesTime.Contract.Models.Users", "ManagerID")
                        .WithMany()
                        .HasForeignKey("ManagerIDUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerID");
                });
#pragma warning restore 612, 618
        }
    }
}
